# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TopoJsonWriter
                                 A QGIS plugin
 Write vector layers to TopoJson
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-01-13
        copyright            : (C) 2021 by Dror Bogin
        email                : Dror.Bogin@Gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TopoJsonWriter class from file TopoJsonWriter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .topojson_writer import TopoJsonWriter
    return TopoJsonWriter(iface)
